#@ load("@ytt:data", "data")
#@ load("deployment.star",
#@  "java_opts",
#@  "config_dir",
#@  "secrets_dir",
#@  "truststore_file")
#@ load("secrets/ca_certs.star", "has_ca_certs")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uaa
spec:
  selector:
    matchLabels:
      app: uaa-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: uaa-deployment
    spec: #! pod spec
      serviceAccountName: uaa
#@ if has_ca_certs(data.values.ca_certs):
      initContainers:
      - name: build-uaa-truststore
        image: openjdk:11
        command:
        - 'sh'
        - '-c'
        - |
          import_cert() {
            local truststore_path="${1}"
            local pemfile="${2}"
            local alias="${3}"

            "${JAVA_HOME}"/bin/keytool \
              -noprompt \
              -import \
              -file "${pemfile}" \
              -trustcacerts \
              -alias "${alias}" \
              -keystore "${truststore_path}" \
              -storepass changeit
          }

          get_alias() {
            basename "${1}" .pem
          }

          build_truststore() {
            local truststore_path="${1}"

            for cert in $SECRETS_DIR/ca_certs/*.pem; do
              local alias="$(get_alias $cert)"
              import_cert "${truststore_path}" "${cert}" "${alias}"
            done
          }

          main() {
            local truststore_path="$(mktemp -d)/temp-truststore"

            build_truststore "${truststore_path}"
            cp "${truststore_path}" "${TRUSTSTORE_FILE}"
          }

          main
        env:
        - name: SECRETS_DIR
          value: #@ secrets_dir
        - name: TRUSTSTORE_FILE
          value: #@ truststore_file
        volumeMounts:
        - name: ca-certs-files
          mountPath: #@ "{}/ca_certs".format(secrets_dir)
          readOnly: true
        - name: truststore-file
          mountPath: /etc/truststore
#@ end
      containers:
      - name: uaa
        image: #@ data.values.image
        resources:
          requests:
            memory: #@ data.values.resources.requests.memory
            cpu: #@ data.values.resources.requests.cpu
        ports:
        - name: http-uaa
          containerPort: 8080
          protocol: TCP
        env:
        - name: BPL_TOMCAT_ACCESS_LOGGING
          value: #@ data.values.tomcat.accessLoggingEnabled
        - name: JAVA_OPTS
          value: #@ java_opts(data.values.database.scheme)
        volumeMounts:
        - name: uaa-config
          mountPath: #@ config_dir
        - name: smtp-credentials-file
          mountPath: #@ "{}/smtp_credentials.yml".format(secrets_dir)
          subPath: smtp_credentials.yml
          readOnly: true
        - name: database-credentials-file
          mountPath: #@ "{}/database_credentials.yml".format(secrets_dir)
          subPath: database_credentials.yml
          readOnly: true
        - name: admin-client-credentials-file
          mountPath: #@ "{}/admin_client_credentials.yml".format(secrets_dir)
          subPath: admin_client_credentials.yml
          readOnly: true
        - name: jwt-policy-signing-keys-file
          mountPath: #@ "{}/jwt_policy_signing_keys.yml".format(secrets_dir)
          subPath: jwt_policy_signing_keys.yml
          readOnly: true
#@ if has_ca_certs(data.values.ca_certs):
        - name: truststore-file
          mountPath: /etc/truststore
          readOnly: true
#@ end
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-uaa
          failureThreshold: 25
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: http-uaa
      volumes:
      - name: uaa-config
        configMap:
          name: uaa-config
      - name: smtp-credentials-file
        secret:
          optional: true
          secretName: uaa-smtp-credentials
      - name: database-credentials-file
        secret:
          optional: true
          secretName: uaa-database-credentials
      - name: admin-client-credentials-file
        secret:
          secretName: uaa-admin-client-credentials
      - name: jwt-policy-signing-keys-file
        secret:
          secretName: uaa-jwt-policy-signing-keys
#@ if has_ca_certs(data.values.ca_certs):
      - name: ca-certs-files
        secret:
          optional: true
          secretName: uaa-ca-certs
      - name: truststore-file
        emptyDir: {}
#@ end
